### ISSUE TITLE
Single header contains #include <flux/..>

### ISSUE THREAD

**Issue by matthew-8925** [tcbrindle/flux#221] opened 2024-11-26 22:44 UTC
Hi,

FYI - the single include contains `#include <flux/core/detail/jtckdint.h>` - which makes it no longer a single file header and won't work on godbolt, etc.
https://github.com/tcbrindle/flux/blob/9a02b77d73f6264a77111acecfb2f572ff478a94/single_include/flux.hpp#L968

Could be useful to add a precommit hook just grep'ing the single include file for `#include "...` or `#include <flux/..`, if this slips through often.

Thanks!

**Comment by tcbrindle** [comment] 2024-11-26 23:14
Hi @matthew-8925, thanks for the bug report! 

The problem is that the single header builder was only looking for files ending `.hpp`, so the new header ending `.h` got skipped. It should be fixed in #222.

> Could be useful to add a precommit hook just grep'ing the single include file for #include "... or #include <flux/.., if this slips through often.

As far as I know this is the first time it's happened, and hopefully the last! I'd definitely consider a check if it happens again -- I guess the Github Actions job that builds the single header on commits to main would be the right place?

**Closed** 2024-11-27 09:20 UTC
